config/routes.rb
Rails.application.routes.draw do

  root to: "organisations#index"

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resources :organisations do
    resources :programmes, only: [:index, :new, :create]
  end

  resources :programmes do
    resources :clients, only: [:new, :create, :index]
  end

  resources :clients do
    resources :outcomes, only: [:index, :new, :create, :show]
  end

  resources :outcomes, only: [:index, :new, :create, :show]

  resources :clients_programmes, only: [:index, :new, :create, :show, :edit, :update]

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :programmes
  validates :name, presence: true
  validates :website, presence: true
  validates :name, uniqueness: true
  validates :website, uniqueness: true

  def website_domain
    self.website.split("www.").last
  end
end 

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController

    def index
      @organisations = Organisation.all
      #explicit rendering; responds to request type
      respond_to do |format|
        format.html {render :index}
        format.json {render json: @organisations}
      end
    end

    def show
      @organisation = Organisation.find(params[:id])
      @programme = Programme.new
      respond_to do |format|
        format.html {render :show}
        format.json {render json: @organisation}
      end
    end

    def new
      @organisation = Organisation.new
    end

    def create
      # binding.pry
      @organisation = Organisation.new(org_params)
        if @organisation.save
          respond_to do |f|
  				f.html {render :index}
  				f.json {render json: @organisations}
  			end
      else
        render :new
      end
    end

    def edit
      @organisation = Organisation.find(params[:id])
      respond_to do |format|
        format.html {render :show}
        format.json {render json: @organisation}
      end
    end

    def update
      @organisation = Organisation.find(params[:id])
      @organisation.update(org_params)
      redirect_to organisation_path(@organisation)
    end

    def destroy
      @organisation = Organisation.find(params[:id]).destroy
      redirect_to organisations_path
    end

    private

    def org_params
      params.require(:organisation).permit(:name, :website)
    end

end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/organisations/_form.html.erb
<%= bootstrap_form_for @organisation do |f| %>
  <%= f.text_field :name %><p>
  <%= f.text_field :website %><p>
  <%= f.submit %>
<% end %>

app/views/organisations/index.html.erb
<div class="greeting">
  <p>Welcome, <%= current_user.email %></p>
</div>

<div class="summary">
  <p>Choose or create your organisation below.</p>
</div>

<%= link_to "Create a New Organisation", new_organisation_path, id: "new-org-form-link" %>

<div id="new-org-form-div">
  <%= bootstrap_form_for Organisation.new do |f| %>
    <%= f.text_field :name %><p>
    <%= f.text_field :website %><p>
    <%= f.submit %>
  <% end %>
</div>

<h2>Organisations</h2>
  <div id="organisations-index">
  </div>

app/views/organisations/new.html.erb
<h2>New Organisation</h2>
<%= render 'form', organisation: @organisation %>

app/views/organisations/show.html.erb
<h3><%= @organisation.name %></h3>

<h4>Current Programmes</h4>
  <% @organisation.programmes.each do |programme| %>
    <ul>
      <li>
        <a href="#" class="programme-link" data-id="<%= programme.id %>"><%= programme.title %></a>
      </li>
      <div class="programme-<%= programme.id %>-clients" data-id="<%= programme.id %>">
      </div>
    </ul>
  <% end %>

<p><%= link_to "Add a new Programme", new_organisation_programme_path(@organisation) %></p>
<p><%= link_to "Edit Organisation", edit_organisation_path(@organisation)%></p>

<%= form_tag organisation_path(@organisation.id), method: "delete" do %>
  <%= submit_tag "Delete #{@organisation.name}" %>
<% end %>