config/routes.rb
Rails.application.routes.draw do

  root to: "organisations#index"

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resources :organisations do
    resources :programmes, only: [:index, :new, :create]
  end

  resources :programmes do
    resources :clients, only: [:new, :create, :index]
  end

  resources :clients do
    resources :outcomes, only: [:index, :new, :create, :show]
  end

  resources :outcomes, only: [:index, :new, :create, :show]

  resources :clients_programmes, only: [:index, :new, :create, :show, :edit, :update]

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

end

app/models/client.rb
class Client < ApplicationRecord
  has_many :clients_programmes
  has_many :programmes, through: :clients_programmes
  has_many :outcomes
  validates :first_name, :last_name, :email, presence: true
  validates :first_name, :last_name, :email, uniqueness: true

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def full_address
    self.address1 + ", " + self.address2
  end

  def clients_programme_object(programme)
    self.clients_programmes.where(:programme_id => programme.id)
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    #work dually with nested route vs accessing all clients in database
    if params.has_key?(:programme_id)
      programme = Programme.find(params[:programme_id])
      clients = programme.clients
      render json: clients
    else
      @clients = Client.all
    end
  end

  def show
    @client = Client.find(params[:id])
    @programme = @client.clients_programmes.find_by(programme_id: params[:programme_id])
    @clients_programmes = @client.clients_programmes

    respond_to do |format|
      format.html {render :show}
      format.json {render json: @client}
      format.json {render json: @clients_programmes}
    end
  end

  def new
    @programme = Programme.find(params[:programme_id])
    @client = @programme.clients.new
  end

  def create
    @programme = Programme.find(params[:programme_id])
    # raise params.inspect
    @client = Client.find_by(id: client_params[:id]) || Client.new(client_params)
    if @client.id
      flash[:notice] = "Your Client has been added to #{@programme.title}"
      val =  "Your Client has been added to #{@programme.title}"
    elsif @client.save
      flash[:notice] = "Your Client was Created"
      val =  "Your Client was Created"
    else
      render :new
      val =  'in else block'
    end
    # byebug
    @client.programmes << @programme
    ClientsProgramme.last.update(client_status_params)
    redirect_to client_path(@client)
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to @client
    else
      render :show
    end
  end

  private

    def client_params
      params.require(:client).permit(:first_name, :last_name, :email, :phone, :address1, :address2, :city, :post_code, :country, :id)
    end

    def client_status_params
      params.require(:client).require(:clients_programme).permit(:client_status, :programme_term, :programme_year, :client_id, :programme_id)
    end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<%= bootstrap_form_for([@programme, @client]) do |f| %>

  <%= f.hidden_field :client_id, value: @client.id %>

  <%= f.text_field :first_name %>
  <%= f.text_field :last_name %>
  <%= f.text_field :email %><p>
  <%= f.text_field :phone %><p>
  <%= f.text_field :address1 %><p>
  <%= f.text_field :address2 %><p>
  <%= f.text_field :city %><p>
  <%= f.text_field :post_code %><p>
  <%= f.text_field :country %><p>
  <%= f.submit "Update Client"%>
<% end %>

app/views/clients/index.html.erb
<h2>All Clients</h2>
<% @clients.each do |client| %>
  <ul>
    <li><%= link_to client.full_name, client_path(client) %></li>
  </ul>
<% end %>

app/views/clients/new.html.erb
<h4>Add a Client to <%= @programme.title %></h4>

<%= bootstrap_form_for([@programme, @client]) do |f| %>
  <%= f.collection_select(:full_name, Client.all, :id, :full_name, {prompt: true}, {name: 'client[id]'}) %>
  <%= f.hidden_field :client_id, value: @client.id %>

<p>or create one:</p>

  <%= f.text_field :first_name %>
  <%= f.text_field :last_name %>
  <%= f.text_field :email %><p>
  <%= f.text_field :phone %><p>
  <%= f.text_field :address1 %><p>
  <%= f.text_field :address2 %><p>
  <%= f.text_field :city %><p>
  <%= f.text_field :post_code %><p>
  <%= f.text_field :country %><p>

<!-- Insert info about ClientsProgramme including status, term and year %> -->

  <%= f.fields_for(ClientsProgramme.new) do |cp| %>
    <%= cp.text_field :programme_term %>
    <%= cp.text_field :programme_year%>
    <%= cp.label "Enrolled?" %>
    <%= cp.radio_button(:client_status, "false") %></p>
    <%= cp.radio_button(:client_status, "true") %></p>
  <% end %>
  <%= f.submit "Add Client"%>
<% end %>

app/views/clients/show.html.erb
<div class="client-id" data-id="<%= @client.id %>">
  <div id="client-name">
    <h2><%= @client.full_name %></h2>
  </div>
</div>

<div id="more-button">
  <input class="btn btn-secondary" name="more" type="button" value="Contact Details">
</div>

<div id="contact_details">

</div>
<p><%= link_to "Edit Client", edit_client_path(@client) %></p>

<p><%= link_to "Add a new Outcome", new_client_outcome_path(@client) %> for <b><%= @client.full_name %></b></p>

<p><%= link_to "View Client Outcomes", client_outcomes_path(@client) %></p>