config/routes.rb
Rails.application.routes.draw do

  root to: "organisations#index"

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resources :organisations do
    resources :programmes, only: [:index, :new, :create]
  end

  resources :programmes do
    resources :clients, only: [:new, :create, :index]
  end

  resources :clients do
    resources :outcomes, only: [:index, :new, :create, :show]
  end

  resources :outcomes, only: [:index, :new, :create, :show]

  resources :clients_programmes, only: [:index, :new, :create, :show, :edit, :update]

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

end

app/models/client.rb
class Client < ApplicationRecord
  has_many :clients_programmes
  has_many :programmes, through: :clients_programmes
  has_many :outcomes
  validates :first_name, :last_name, :email, presence: true
  validates :first_name, :last_name, :email, uniqueness: true

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def full_address
    self.address1 + ", " + self.address2
  end

  def clients_programme_object(programme)
    self.clients_programmes.where(:programme_id => programme.id)
  end

end

app/models/outcome.rb
class Outcome < ApplicationRecord
  belongs_to :client
  validates :grade, :description, presence: true
end

app/controllers/outcomes_controller.rb
class OutcomesController < ApplicationController

  def index
    @outcomes = Outcome.all
    @client = Client.find(params[:client_id])
  end

  def show
    @outcome = Outcome.find(params[:id])
    @client = Client.find(params[:client_id])
    @programme = @client.programmes
    @outcomes = @client.outcomes
  end

  def new
    @client = Client.find(params[:client_id])
    @programmes = @client.programmes
    @outcome = @client.outcomes.new
  end

  def create
    @client = Client.find(params[:client_id])
    @outcome = @client.outcomes.build(outcome_params)
    if @outcome.save
      flash[:notice] = "Your Outcome was Created."
      redirect_to client_outcomes_path
    else
      render :new
    end
  end

  private

    def outcome_params
      params.require(:outcome).permit(:grade, :description)
    end

end

app/helpers/outcomes_helper.rb
module OutcomesHelper
end

app/views/outcomes/index.html.erb
<h2>Outcomes</h2>
<% @outcomes.each do |outcome| %>
  <p>Grade: <%= outcome.grade %></p>
  <p>Description: <%= outcome.description %></p>
<% end %>

<p><%= link_to "Return to Client Page", client_path(@client) %></p>

app/views/outcomes/new.html.erb
<p>Add a new Outcome for <b><%= @client.full_name %></b>.</p>

<%= bootstrap_form_for ([@client, @outcome]) do |f| %>
  <%= f.text_field :grade %><p>
  <%= f.text_field :description %><p>
  <%= f.submit %>
<% end %>

app/views/outcomes/show.html.erb
<h2>Outcomes</h2>
<% @client.outcomes.each do |outcome| %>
  <p>Grade: <%= outcome.grade %></p>
  <p>Description: <%= outcome.description %></p>
<% end %>

<p><%= link_to "Create a New Outcome", new_client_outcome_path(@client, @outcome) %></p>

<p><%= link_to "Return to Client Page", programme_client_path(@client.programme_ids, @client.id) %></p>