config/routes.rb
Rails.application.routes.draw do

  root to: "organisations#index"

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resources :organisations do
    resources :programmes, only: [:index, :new, :create]
  end

  resources :programmes do
    resources :clients, only: [:new, :create, :index]
  end

  resources :clients do
    resources :outcomes, only: [:index, :new, :create, :show]
  end

  resources :outcomes, only: [:index, :new, :create, :show]

  resources :clients_programmes, only: [:index, :new, :create, :show, :edit, :update]

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NovaCRM</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">

        <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
        <% end %>

        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> |
            <%= link_to "Home", root_path, :class => 'navbar-link' %> |
            <%= link_to "Organisations", organisations_path, :class => 'navbar-link' %> |
            <%= link_to "Clients", clients_path, :class => 'navbar-link' %> |

          <% else %>

          <% end %>
        </p>
      </div>
    </div>
    <div="app-summary"><i><b>Nova CRM</b> manages your programmes, clients and their outcomes.</i>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">

      <%= yield %>

    </div>
  </div>
</div>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" />
</body>

</html>